server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# set eureka.client.registerWithEureka false and fetchRegistry false to ideantify a eureka server.